### ISSUE TITLE
Return list of photos by hash tag.

### ISSUE THREAD

**Issue by cnizzardini** [NicklasWallgren/instagram-api#1]
Return list of photos by hash tag. 

IG used to allow this via their API but then removed it. If you can add this I'll give it a go on my works website to replace that functionality.

Thanks.

**Comment by NicklasWallgren** [comment]
I have added initial support for the feed endpoint. I'll finish it up tomorrow.

Example code, you'll be able to access the feeds and tags method directly from the Instagram instance in the next commit.

Have a look at;
```Instagram\SDK\Client\Features\HashtagFeaturesTrait```

Example
```
// Retrieve the feed
$feed = $instagram->client->feed('INSERT TAG');

$feed->getRankedItems();
$feed->getItems();

// Retrieve the next batch of items 
$result = $feed->next();
```

**Comment by NicklasWallgren** [comment]
https://github.com/NicklasWallgren/instagram-api/tree/v0.7.6

The release was a bit rushed since I'm going away for a few days, so the API might change in future updates. 

Feed example
```
// Retrieve hashtag feed
$message = $instagram->feed('instagram', Instagram::$FEED_TYPE_HASHTAG);

// Output top result
var_dump($message->getRankedItems());
```


Search example
```
// Search by hashtag
$message = $instagram->search('instagram', Instagram::$FEED_TYPE_HASHTAG);

// Retrieve the results collection
$result = $message->getResults();

// Pick the first entry
$hashtag = current($result);

// Retrieve the hashtag feed
$feed = $hashtag->getFeed();

// Output items
var_dump($feed->getRankedItems());
```

**Comment by cnizzardini** [comment]
Damn, wish I could test this out, but the site I am working on runs off 5.6 and you're using 7.x only language features.  I'll test this out again when we get around to upgrading.

**Comment by NicklasWallgren** [comment]
No worries. Can we close this issue? :)

**Comment by cnizzardini** [comment]
Your call.

**Comment by NicklasWallgren** [comment]
Resolved.
