### ISSUE TITLE
get pending inbox

### ISSUE THREAD

**Issue by valkiriy** [NicklasWallgren/instagram-api#14]
hi. how i get pending inbox and confirm then?
and
How to mark the thread read?

**Comment by NicklasWallgren** [comment]
Hey, It isn't possible at this time. I'll add the functionality in an upcoming release.

You are welcome to help out and create a PR.

**Comment by NicklasWallgren** [comment]
This will soon be available as of https://github.com/NicklasWallgren/instagram-api/tree/feature/inbox-confirm-and-get-unseen

```
$unseen = $message->getInbox()->getUnseen();

foreach ($unseen as $threadId => $unseenItemsInThread) {
    /**
     * @var ThreadItem $threadItem
     */
    $threadItem = current($unseenItemsInThread);

    $threadItem->seen();
}
```

**Comment by valkiriy** [comment]
Thanks!

**Comment by NicklasWallgren** [comment]
The feature has been merged into master.
