### ISSUE TITLE
Any plans for supporting endpoints to retrieve followers/following lists?

### ISSUE THREAD

**Issue by mferrara** [NicklasWallgren/instagram-api#19]
As far as I can see there's no support for followers/following in the library.. are there any plans to support this data?

I'd be open to working it out and submitting a PR but I really don't know where to start in terms of how you're determining the endpoints and parameters to them that are required.

**Comment by NicklasWallgren** [comment]
Sure, have a look at the following feature branch, https://github.com/NicklasWallgren/instagram-api/tree/feature/retrieve-followers.

https://github.com/NicklasWallgren/instagram-api/blob/a9b747c544050d00356af7bd88bf90417cc1e6a1/src/Client/Features/FriendshipsFeaturesTrait.php#L112

The `following` endpoint is fairly simple and similar to the `followers` endpoint. The response is identical.

```
GET
api/v1/friendships/<user id>/following/?rank_token=<rank token>
```

I'm using a proxy to determine the traffic between the IOS client and the API.

**Comment by NicklasWallgren** [comment]
Implemented and merged. https://github.com/NicklasWallgren/instagram-api/pull/20
