### ISSUE TITLE
searchByHashtag

### ISSUE THREAD

**Issue by adamlaashiri** [NicklasWallgren/instagram-api#29]
$instagram->searchByHashtag('dog'); only leaves me with a fatal error and so does a couple of other traits such as searchByUser and feedByHashtag etc... 

**Fatal error**: Uncaught Instagram\SDK\Responses\Exceptions\ApiResponseException in /api/exp/vendor/nicklasw/instagram-api/src/Responses/Serializers/AbstractSerializer.php:99 Stack trace: #0 /api/exp/vendor/nicklasw/instagram-api/src/Responses/Serializers/AbstractSerializer.php(50): Instagram\SDK\Responses\Serializers\AbstractSerializer->handleInvalidHttpResponse() #1 /api/exp/vendor/nicklasw/instagram-api/src/Requests/Traits/RequestMethods.php(216): Instagram\SDK\Responses\Serializers\AbstractSerializer->decode() #2 /api/exp/vendor/nicklasw/instagram-api/src/Support/Promises/functions.php(36): Instagram\SDK\Requests\GenericRequest->Instagram\SDK\Requests\Traits\{closure}() #3 /api/exp/vendor/guzzlehttp/promises/src/TaskQueue.php(48): Instagram\SDK\Support\Promises\{closure}() #4 /api/exp/vendor/nicklasw/instagram-api/src/Http/Guzzle/Handlers/CurlMultiHa in /api/exp/vendor/nicklasw/instagram-api/src/Responses/Serializers/AbstractSerializer.php on line 99

**Comment by NicklasWallgren** [comment]
Hey, 

The issue has been fixed in the latest PR.
