### ISSUE TITLE
Get user info by username

### ISSUE THREAD

**Issue by furkan6116** [NicklasWallgren/instagram-api#33]
Hi ı just trying to get spesicified users profile picture and full name by username. 

I searched everywhere but ı did not find anything about it.

Can anyone help me please

**Comment by furkan6116** [comment]
Hey.

I really need that function, ı searched all php packages about instagram, but ı did not found anything.
if you will extend that function to this project. It would be very good my friend.

Regards
Furkan

**Comment by NicklasWallgren** [comment]
@furkan6116 Alright. I'll add the the functionality later today.

**Comment by NicklasWallgren** [comment]
Added in the latest release. Closing this issue.

**Comment by patriotaki** [comment]
how can this be used? how can we find which functions are available is there any documentation?

**Comment by NicklasWallgren** [comment]
@patriotaki 
You can use the `userByName` method, ie

```
$response = $instagram->userByName('dogsofinstagram');
```

There isn't any documentation available, but you can find all available methods in `src/Traits`
