### ISSUE TITLE
The cookie csrftoken is missing in the cookie jar

### ISSUE THREAD

**Issue by monsterJKB** [NicklasWallgren/instagram-api#36]
The cookie csrftoken is missing in the cookie jar

**Comment by NicklasWallgren** [comment]
I haven't noticed this particular issue. Could you please review it again tomorrow, once I have commited the latest release.

**Comment by NicklasWallgren** [comment]
@monsterJKB I'll be releasing https://github.com/NicklasWallgren/instagram-api/pull/38 in a few hours. Can you please verify if this issue still exists.
