### ISSUE TITLE
Feed API not working anymore

### ISSUE THREAD

**Issue by EmanueleCoppola** [NicklasWallgren/instagram-api#37]
It seems that the API to get the feed by the user is not working anymore.
This is the response that I get from the Guzzle client.
I saw that the new API could be something like /users/**_USERNAME_**/media/recent/
I didn't go deeper in this issue, did you?

```
Client error: `POST https://i.instagram.com/api/v1/feed/user/USERNAME/` resulted in a `404 Not Found` response:
<!DOCTYPE html>
<html lang="en" class="no-js logged-in client-root touch">
    <head>
        <meta charset="utf-8">
    (truncated...)

```

**Comment by NicklasWallgren** [comment]
@EmanueleCoppola Hey, It's working fine in my latest branch. I'll release it tomorrow.

**Comment by Mattiam2** [comment]
News about the update?

**Comment by NicklasWallgren** [comment]
@EmanueleCoppola @Mattiam2 

I'll be releasing https://github.com/NicklasWallgren/instagram-api/pull/38 in a few hours. Could you please verify that the feed API is working for you?

Have a look at https://github.com/NicklasWallgren/instagram-api/blob/feature/remove-redundant-requests-and-serializers/examples/feed_by_user.php

Please bear in mind that this PR brings some major changes to the API, in preparations for the upcoming 1.0 release.

**Comment by NicklasWallgren** [comment]
Please try out the latest release, and open a new ticket if the issue persist.
