### ISSUE TITLE
How to start a new thread to a specific user? (direct message)

### ISSUE THREAD

**Issue by VarroReve** [NicklasWallgren/instagram-api#40]
Hi Nicklas, I found the `sendThreadMessage()` function which can send messages to an existing thread, but I'd like to start a new thread by input their `username` (sending a direct message by username), can u tell me how to achieve that?

**Comment by VarroReve** [comment]
I managed to achieve it. close now

**Comment by sanjeetbisht** [comment]
> I managed to achieve it. close now

I can you help me? 
how did you achieved it?
