### ISSUE TITLE
guzzlehttp/guzzle ^6.2 conflicts with Laravel 8 requires guzzlehttp/guzzle ^7.0.1

### ISSUE THREAD

**Issue by chhaihongsrun** [NicklasWallgren/instagram-api#44]
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Root composer.json requires nicklasw/instagram-api ^0.10.0 -> satisfiable by nicklasw/instagram-api[v0.10.0].
    - nicklasw/instagram-api v0.10.0 requires guzzlehttp/guzzle ^6.2 -> found guzzlehttp/guzzle[6.2.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).

Please, package to support multiple guzzlehttp/guzzle.

* I don't other way to fix it, I make it work by downloading it then load it locally by changing the composer.json: "guzzlehttp/guzzle": "^6.2|^7.0.1",

**Comment by NicklasWallgren** [comment]
@chhaihongsrun Good idea, could you create a PR?

The following versions should be interchangeable.
`"guzzlehttp/guzzle": "^6.0|^7.0"`

**Comment by chhaihongsrun** [comment]
I had created PR. Please, kindly check it.
https://github.com/NicklasWallgren/instagram-api/pull/45

**Comment by NicklasWallgren** [comment]
Fixed in https://github.com/NicklasWallgren/instagram-api/releases/tag/v0.10.1
