### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by roottusk** [NicklasWallgren/instagram-api#7]
Fatal error: Uncaught TypeError: Return value of Instagram\SDK\DTO\General\User::getId() must be of the type integer, float returned in C:\xampp\vendor\nicklasw\instagram-api\src\DTO\General\User.php:62
Stack trace:
#0 C:\xampp\vendor\nicklasw\instagram-api\src\DTO\Direct\Thread.php(560): Instagram\SDK\DTO\General\User->getId()
#1 C:\xampp\vendor\nicklasw\instagram-api\src\Responses\Serializers\Traits\OnPropagateDecodeEventTrait.php(45): Instagram\SDK\DTO\Direct\Thread->onDecodeUsers()
#2 C:\xampp\vendor\nicklasw\instagram-api\src\DTO\Direct\Thread.php(550): Instagram\SDK\DTO\Direct\Thread->propagate(Array)
#3 C:\xampp\vendor\nicklasw\instagram-api\src\Responses\Serializers\Traits\OnPropagateDecodeEventTrait.php(71): Instagram\SDK\DTO\Direct\Thread->onDecode(Array, Array)
#4 C:\xampp\vendor\nicklasw\instagram-api\src\Responses\Serializers\Traits\OnPropagateDecodeEventTrait.php(48): Instagram\SDK\DTO\Direct\Inbox->invokeDecodeEventListener(Array, Array)
#5 C:\xampp\vendor\nicklasw\instagram-api\src\DTO\Direct\Inbox.php(129 in C:\xampp\vendor\nicklasw\instagram-api\src\DTO\General\User.php on line 62

**Comment by NicklasWallgren** [comment]
Interesting, I'll look into it.
