### ISSUE TITLE
I couldnt get to run any of the examples .

### ISSUE THREAD

**Issue by roottusk** [NicklasWallgren/instagram-api#8]
Fatal error: Uncaught TypeError: Return value of Instagram\SDK\DTO\Direct\ThreadItem::getUserId() must be of the type integer, float returned in C:\xampp\vendor\nicklasw\instagram-api\src\DTO\Direct\ThreadItem.php:77
Stack trace:
#0 C:\xampp\vendor\nicklasw\instagram-api\src\Responses\Serializers\Traits\OnPropagateDecodeEventTrait.php(199): Instagram\SDK\DTO\Direct\ThreadItem->getUserId()
#1 C:\xampp\vendor\nicklasw\instagram-api\src\Responses\Serializers\Traits\OnPropagateDecodeEventTrait.php(173): Instagram\SDK\DTO\Direct\Thread->getRequirementParameterValue(Object(Instagram\SDK\DTO\Direct\ThreadItem), 'userId')
#2 [internal function]: Instagram\SDK\DTO\Direct\Thread->Instagram\SDK\Responses\Serializers\Traits\{closure}('userId')
#3 C:\xampp\vendor\nicklasw\instagram-api\src\Responses\Serializers\Traits\OnPropagateDecodeEventTrait.php(174): array_map(Object(Closure), Array)
#4 C:\xampp\vendor\nicklasw\instagram-api\src\Responses\Serializers\Traits\OnPropagateDecodeEventTrait.php(144): Instagram\SDK\DTO\Direct\Thread->ge in C:\xampp\vendor\nicklasw\instagram-api\src\DTO\Direct\ThreadItem.php on line 77

**Comment by roottusk** [comment]
Thanks for the previous commit

**Comment by NicklasWallgren** [comment]
Right, are you running with strict_types enabled? Check out my latest commit.

Regards
Nicklas

**Comment by roottusk** [comment]
No,I am not maybe.Do you have an IM handle something or Can I get your email?

**Comment by NicklasWallgren** [comment]
Did you try the latest commit? (the amended one).

You can reach me at nicklas.wallgren@gmail.com.

**Comment by roottusk** [comment]
Yes I tried latest ..

**Comment by NicklasWallgren** [comment]
Well, you shouldn't get the same type of error with the latest commit. I have tried with two different accounts and It works fine.

**Comment by NicklasWallgren** [comment]
Closing this issue. Could not reproduce.
